ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.example.rhnaf.ApplicationKt.module ]
    }
    huggingface {
        api_key = ${?HF_API_KEY}
    }
}
